### ISSUE TITLE
Open Source Malware Infection

### ISSUE THREAD

**Issue by BaerBriston** [certificate-helper/TLS-Inspector#113]
I have lost a Samsung Android and DELL XPS due to the open source licenced code malware by the names of SQLite, Coverage,Xdg-Utils, mock, just to name a few from a long list. Some are derived from Apache code, others from github code. Can  anyone suggest how to identify these and remove them??

I literally have a DELL INSPIRON 27775, Sony Experia, and now a Toshiba laptop fully infected. 

Any help would be appreciated.

**Comment by ecnepsnai** [comment]
This is not the place to request support for anything unrelated to the TLS Inspector iOS app.
