### ISSUE TITLE
Exit / crash when sharing to TLS-Inspector and tapping View All headers

### ISSUE THREAD

**Issue by fallingrock** [certificate-helper/TLS-Inspector#133]
**Affected Version:** 1.8.4

**Is this a Test Flight version or the App Store version?** Test flight

**Device and iOS Version:**. iPhone 8 iOS 12.1.4

**What steps will reproduce the problem?**

1. Open a website in safari
2. Tap share button in browser.
3. Tap Show Certificate
4. Scroll to bottom
5. Tap View All
6. Immediately returned to browser.

**What is the expected output?**
More information about headers

**What do you see instead?**
Exits / crashes directly back to browser.

**Please provide any additional information below.**
If TLS Inspector is launched as a stand alone app, the more info button works fine.

**Comment by ecnepsnai** [comment]
Thanks for reporting this. I can reproduce this as well and will schedule a hotfix.
