### ISSUE TITLE
https://github.com/certificate-helper/TLS-Inspector/issues/149

### ISSUE THREAD

**Issue by kh00** [certificate-helper/TLS-Inspector#150]
**Affected Version:**

**Is this a Test Flight version or the App Store version?**

**Device and iOS Version:**

**What steps will reproduce the problem?**

1.
2.
3.

**What is the expected output?**

**What do you see instead?**

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment]
@kh00 repeatedly opening invalid issues is spam. I am blocking your ability to open any new issues for 10 days. Further infractions will result in a permanent ban.
