### ISSUE TITLE
Add ability to generate private key & X.509 server certificate from within the app

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#16]

**Comment by martinseener** [comment]
For what do you want to be able to generate a privkey and server cert from within the app? i don't see the benefit

**Comment by ecnepsnai** [comment]
It was just an idea I had so I made a bug to track it.

**Comment by marinofaggiana** [comment]
@ecnepsnai Hi, I search a wrapper for create private key and certificate X509 ... do you know a wrapper for this ?

Thanks

**Comment by ecnepsnai** [comment]
@marinofaggiana It's still in very early development, but we offer a macOS GUI application to generate X509 certificates and private keys here: https://github.com/certificate-helper/Certificate-Factory/releases

**Comment by marinofaggiana** [comment]
oh ! sound good !!

**Comment by ecnepsnai** [comment]
Closing this issue in favour of the Certificate Factory project.
