### ISSUE TITLE
TLS 1.3 support 

### ISSUE THREAD

**Issue by frank-f** [certificate-helper/TLS-Inspector#160]
Hi!

Since I saw, that you updated to OpenSSL 1.1.1 I was hoping you finally implemented TLS 1.3 as well. Sadly I had to see you did not. Any reason for that? The library does support it.

Kind regards

**Comment by ecnepsnai** [comment]
You need to switch the crypto engine to OpenSSL in the advanced settings of the app.

By default, TLS Inspector defaults to using the iOS Socket library which does not default to TLS 1.3 yet.

**Comment by frank-f** [comment]
That indeed works. Safari on iOS is capable of TLS 1.3 - are apps not using the same crypto engine?
