### ISSUE TITLE
Connection information section shows incorrect IP(v6) - NOT actual webserver

### ISSUE THREAD

**Issue by vom513** [certificate-helper/TLS-Inspector#175]
**Affected Version:**

2.0.2(73)

**Is this a Test Flight version or the App Store version?**

App Store

**Device and iOS Version:**

iPhone X - 13.3.1

**What steps will reproduce the problem?**

1. Enter "burn.net" into app.
2. Observe "connection information".

**What is the expected output?**

The IP address of burn.net: 2607:f2f8:a4c8::2

**What do you see instead?**

An IP address from the same prefix, but I have no idea what the specific host bits are corresponding to:

2607:f2f8:a4c8:0:8100:e32b:7d3a:b5a4

**Please provide any additional information below.**

Screenshot - https://imgur.com/a/pGbdXlS

**Comment by vom513** [comment]
Sorry for replying to myself, but I tried another site (arin.net).  Similar behavior.  Looks like the "connection information" has the first 4 hextets correct.  After that it's "8100:e32b:7d3a:b5a4" again for me.

**Comment by ecnepsnai** [comment]
Hi @vom513 what crypto engine are you using (Look under Advanced Settings). Does this problem happen with both iOS and OpenSSL ?

**Comment by vom513** [comment]
It's currently set to iOS (I assume this is the default - I didn't set this).

Setting this to OpenSSL has the same behavior (I put it back in iOS after testing).

A couple more points:

* This also happens on my iPad (latest iPad OS).  
* The "right side" of this address is different now.  I still have the correct leading hextets.  In the case of burn.net - this is 2607:f2f8:a4c8:0.  I notice that this is exactly half the address.

**Comment by ecnepsnai** [comment]
I'm still looking into this. The logic used to get the servers IP address isn't complex so I'm not ruling out that this is potentially an iOS bug.

**Comment by ecnepsnai** [comment]
Fix identified - will be included in next update.

**Comment by vom513** [comment]
Nice - appreciate the work on this.
