### ISSUE TITLE
Option to hide result when sharing to "View on SSL Labs"

### ISSUE THREAD

**Issue by der-knappes** [certificate-helper/TLS-Inspector#184]
When sharing a domain name to "View on SSL Labs" the result of the test will be shared on the dashboard of ssllabs.com ([https://www.ssllabs.com/ssltest/index.html](url)). 
This can be disabled by checking the box "Do not show the results on the boards" on the query website as well as by appending `&hideResults=on` to the query URL. (e.g. `https://www.ssllabs.com/ssltest/analyze.html?d=github.com&hideResults=on`)

This option control could possibly be implemented by displaying a summary view of the data which will be sent to ssllabs.com and a switch control after selecting "View on SSL Labs" from the share menu. 

This feature would enhance the privacy of a query.

**Comment by ecnepsnai** [comment]
Great idea, I'll probably just set this as the default and skip adding another option (as the options screen is already a bit cluttered)

**Comment by ecnepsnai** [comment]
Included in 2.0.7 release
