### ISSUE TITLE
Improved Handling of LAN Access Permission

### ISSUE THREAD

**Issue by robnightingale** [certificate-helper/TLS-Inspector#245]
### Affected versions:

2.7.3

### Release type

- [ ] This issue applies only to a TestFlight release

### Device Type and iOS Version:

iPhone 12 Pro, iOS 17.0.3

### What steps will reproduce the problem?

I'm running several servers on. my home lan, each with self-signed certs from a private CA (step-ca) for my internal domain.
The phone has the CA root pen installed as a profile and it has been verified/trusted.  Access to the site is perfectly fine, certificates are shown as trusted etc. When activating TLS inspector (via share, show certificate) I receive the 'timed out' error shown below.

### What is the expected output?

I was hoping to see details of the tls trust chain as it does for external sites / public CAs.

### What do you see instead?

I see the timed out error per the attached image.
![IMG_8126](https://github.com/tls-inspector/tls-inspector/assets/3149042/dfa63ca0-eb66-4dfd-8e5c-36f62744302f)

### Any other information to provide?

Happy to help debug if required.

**Comment by ecnepsnai** [comment]
This is a known issue and one without a good workaround on my end, but an easy fix on your side.

Open the app itself and inspect any resource on your LAN. You should see a permissions dialog appear for local network access. Once approved, inspections from the app and the share extension should work.

If no permission dialog appears, check iOS settings -> Privacy -> Local Network.

**Comment by robnightingale** [comment]
Thank you for the speedy response and apologies if I missed the known issue. I hadn't tried using the TLS app as a native app before, and your suggestion got me working. Many thanks!

**Comment by ecnepsnai** [comment]
According to [this thread](https://developer.apple.com/forums/thread/650648) there is no way to actively request local network permission, and the error we get back from the APIs do not indicate anything specific to this permission. Closing this as there's nothing we can do from the app.
