### ISSUE TITLE
Distinguish Certificates Loaded from Trust Store vs Sent by Server

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#261]

**Comment by ecnepsnai** [comment]
so funny thing about me using the 'easy' tag

i don't think this is possible with network framework

**Comment by cs-hv** [comment]
I'm sorry to read this but kind a expected an answer like this.
But thanks for taking a look at this!

**Comment by ecnepsnai** [comment]
Closing for now - will keep an eye on if there is an opportunity later.
