### ISSUE TITLE
Highlight EV Certificates

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#34]

**Comment by garz75** [comment]
Version: TestFlight
Some EV certificates policy identifiers are missing from the list you imported. For example the ones from OpenTrust/Docusign France are missing: This is an existing EV certification authority (I used to work for them ;-), they are listed here https://en.wikipedia.org/wiki/Extended_Validation_Certificate#Extended_Validation_certificate_identification but the certificate issued by their EV CA are not highlighted as such by TLS-Inspector.
Test web site: https://webportal.opentrust-cloud.com/ : shown as EV-certified with Safari/FF, not by TLS-Inspector

**Comment by ecnepsnai** [comment]
All of the EV authorities we check for are listed here: https://github.com/certificate-helper/TLS-Inspector/blob/1.5/CertificateKit/CKCertificate.m#L287

We've omitted some (like StartComm and WoSign), however it looks like we accidentally forgot that one.
