### ISSUE TITLE
(null) host name when viewing certificate on SSL labs

### ISSUE THREAD

**Issue by garz75** [certificate-helper/TLS-Inspector#46]
This happens when using the main app, either when opening a site from the history or typing it manually. Once in the detailed view of the certificate, click the share icon at the top and choose Vien on SSL Labs: the internal browser opens at this URL:

https://www.ssllabs.com/ssltest/analyze.html?d=(null)

Version: Testflight...
Does not seem to happen when using the app extension...

Screenshot

![img_0236](https://cloud.githubusercontent.com/assets/6645395/24570160/e3a08e66-161e-11e7-8b43-c9aaf394fe44.PNG)

**Comment by ecnepsnai** [comment]
Awkward, is totally a goof on my end, I have handling for this in the app extension but for whatever reason didn't do it in the main app: https://github.com/certificate-helper/TLS-Inspector/commit/f8c8a1d960181564407559860836035e81e586c0#diff-97ea9fc2cabec5cb4f79e81d30d8e5c2R131

**Comment by garz75** [comment]
That's is why testing and testers are important ;-) They always find new and unexpected ways to use the app... Happy to help!
