### ISSUE TITLE
Text cut off on negotiated cipher content on iPad in portrait orientation

### ISSUE THREAD

**Issue by fallingrock** [certificate-helper/TLS-Inspector#49]
![img_0061](https://cloud.githubusercontent.com/assets/4029821/24587812/cd4f4f98-1782-11e7-8a7f-c2b4582fb013.PNG)

Text cut off on negotiated cipher content on iPad in portrait orientation. 

Displays fine in landscape orientation and on iPhone.

**Comment by fallingrock** [comment]
Also cut off when using safari share. 

![img_0062](https://cloud.githubusercontent.com/assets/4029821/24587878/dc344f94-1783-11e7-8bd7-f2c8d9ee60a1.PNG)

**Comment by ecnepsnai** [comment]
Yeah, I've been struggling with this one myself for a while. Apple makes it really difficult to determine how many lines of text a label is using. In both cases above, it's incorrectly telling us that it's only using a single line of text, so I size the height of the cell for a single line.
