### ISSUE TITLE
Application crashes while loading certificates for some domains

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#63]
**Affected Version:**

1.5.1 (26)

**Is this a Test Flight version or the App Store version?**

App Store

**Device and iOS Version:**

All

**What steps will reproduce the problem?**

1. Inspect in24.de

**What is the expected output?**

Certificate list appears

**What do you see instead?**

App crashes

**Please provide any additional information below.**

Also applies to keltia.net

**Comment by ArnaudFeld** [comment]
Same Problem here:
Try arnaudfeld.de / zieh.es / sieh.es

**Comment by ecnepsnai** [comment]
Crash is occurring because the app was unable to parse the CRL but did not check for a failure and assumed success in CertificateKit.
