### ISSUE TITLE
Problem with share-function from other browsers

### ISSUE THREAD

**Issue by larssonper** [certificate-helper/TLS-Inspector#69]
**Affected Version:**
Multiple? I believe I have had this problem for some time. Now I run 1.5.3.29.1.1.0e

**Is this a Test Flight version or the App Store version?**
No

**Device and iOS Version:**
iPhone 8 iOS 11 and iPhone 7 iOS 11.

**What steps will reproduce the problem?**

1. Start Chrome, Brave, Firefox or Opera Mini.
2. Go to a https-enabled site. Eg https://www.google.com
3. Use the Share-function and select Show Certificate.

**What is the expected output?**
Information about the certificate to be displayed. 

**What do you see instead?**
An error message in TLS-Inspector says " Unsupported Scheme. Only HTTPS sites can be inspected."

**Please provide any additional information below.**
It works on Safari and Firefox Focus.

**Comment by ecnepsnai** [comment]
Hello @larssonper, thank you for opening this issue. I can verify that I also have the same problem with Brave. I will investigate and include a fix in the next update of TLS Inspector.

**Comment by ecnepsnai** [comment]
There appears to be two bugs here.

1. Is that the current logic prevents any third party browser from working. This bug will track this issue.
2. Brave is not compatible with the app at the moment. This is an issue with Brave and has been reported here: https://github.com/brave/browser-ios/issues/1193

**Comment by ecnepsnai** [comment]
With the latest update to Brave for iOS the Show Certificate extension works in the browser now
