### ISSUE TITLE
Broken link to a beta sign app document

### ISSUE THREAD

**Issue by timothybasanov** [certificate-helper/TLS-Inspector#72]
**What steps will reproduce the problem?**

1. Open CONTRIBUTING.md
2. Click enroll in beta link

**What is the expected output?**
Enrolling into beta document or site

**What do you see instead?**
Error from Google about code of conduct or something. 

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment]
Hello @timothybasanov 

Yes, we're aware of this problem. We're going to build our own beta sign up system so we can stop using Google Forms. There's no timeline for this.

There will be no code change required for this bug, and the project to add the new sign up system is tracked elsewhere, so I'm going to close this.

**Comment by ecnepsnai** [comment]
Hi @timothybasanov I'm just writing to let you know that we've fixed the beta signup form for TLS Inspector. Let me know if you have any problems with the new system.
