### ISSUE TITLE
App Crashes when CRL distribution list is on non-HTTP/HTTPS server.

### ISSUE THREAD

**Issue by Shan11812** [certificate-helper/TLS-Inspector#81]
**Affected Version:**
1.6.0 (31)

**Is this a Test Flight version or the App Store version?**
App Store

**Device and iOS Version:**
iPad Mini 2 - 9.3.3, iPhone 8 - 11.0.3/11.1.1
iPhone 6 - 11.0.3

**What steps will reproduce the problem?**

1. Create Root CA
2. Create Self Signed Certificate with the root
3. Bind on IIS and install CA on device

**What is the expected output?**
Should show if certificate chain is valid/invalid

**What do you see instead?**
App Crashes

**Comment by ecnepsnai** [comment]
Hi Shan, thank you for the report.

I test TLS Inspector often with self-signed certificates and have not seen this crash.

If possible, could you please email me a copy of the root CA and server certificate (only the certificate, obviously exclude the private key) so I can see what is causing this issue: tls-inspector@ecnepsnai.com

**Comment by Shan11812** [comment]
Hi, I just followed [this blog post](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/) for creating CA and certificates.

Also could you mention the iOS sdk version (target/min) or any other requirements for building the source, getting a bunch of errors when I try.

**Comment by ecnepsnai** [comment]
There aren't any special build requirements, although you will have to disable/change code signing to use your account (as its currently committed to use my account, which is tracked to be changed with: https://github.com/certificate-helper/TLS-Inspector/issues/76

**Comment by Shan11812** [comment]
Was able to build with Xcode 9.1

Crash Log:
```
* Closing connection 0
2017-11-17 12:41:37.703092+0530 TLS Inspector[1979:36412] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110da11ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011043ef41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110de0f9c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000110cd04c5 -[__NSArrayM insertObject:atIndex:] + 1285
	4   CertificateKit                      0x000000010fbc6d5f -[CKCertificate crlDistributionPoints] + 447
	5   CertificateKit                      0x000000010fbcbb84 -[CKGetter streamHasSpaceAvailable:] + 2276
	6   CertificateKit                      0x000000010fbcafa3 -[CKGetter stream:handleEvent:] + 147
	7   CoreFoundation                      0x0000000110d65084 _signalEventSync + 228
	8   CoreFoundation                      0x0000000110d77ef6 _cfstream_solo_signalEventSync + 246
	9   CoreFoundation                      0x0000000110d62f7a _CFStreamSignalEvent + 490
	10  CFNetwork                           0x0000000114fd13e1 _ZN12SocketStream14socketCallbackEP10__CFSocketmPK8__CFDataPKv + 145
	11  CFNetwork                           0x0000000114fd1316 _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv + 70
	12  CoreFoundation                      0x0000000110d62bd1 __CFSocketPerformV0 + 1121
	13  CoreFoundation                      0x0000000110d44231 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	14  CoreFoundation                      0x0000000110de3e41 __CFRunLoopDoSource0 + 81
	15  CoreFoundation                      0x0000000110d28b49 __CFRunLoopDoSources0 + 185
	16  CoreFoundation                      0x0000000110d2812f __CFRunLoopRun + 1279
	17  CoreFoundation                      0x0000000110d279b9 CFRunLoopRunSpecific + 409
	18  GraphicsServices                    0x000000011970c9c6 GSEventRunModal + 62
	19  UIKit                               0x00000001120005e8 UIApplicationMain + 159
	20  TLS Inspector                       0x000000010f5a452f main + 111
	21  libdyld.dylib                       0x0000000117757d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

occurring at [CKCertificate - Line 361](https://github.com/certificate-helper/TLS-Inspector/blob/master/CertificateKit/CKCertificate.m#L361)

url field starts with **ldap:///** and URLWithString is returning nil

**Comment by ecnepsnai** [comment]
Thanks for investigating that for me!

TLS Inspector only supports HTTPS at the moment. We don’t have any plans to support other protocols, but you’re more than welcome to submit a request.

I’m going to use this ticket to track the lack of error handling for unsupported protocols.

**Comment by Shan11812** [comment]
@ecnepsnai the url is CRL distribution url. Since it is self signed, it may not be always be a valid uri

**Comment by ecnepsnai** [comment]
Ah sorry, I was on my phone and didn't look at the code you linked. I'll update the issue.
