### ISSUE TITLE
Include UserAgent header for HTTP Server Info request

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#84]
**Affected Version:**

1.6.0

**Is this a Test Flight version or the App Store version?**

App Store

**Device and iOS Version:**

All

**What steps will reproduce the problem?**

1. Make a request to a HTTP Server that requires a UserAgent Header
2. Request fails

**What is the expected output?**

Request should work

**What do you see instead?**

Request fails, because no user agent was provided

**Please provide any additional information below.**

**Comment by sindarina** [comment]
I would recommend using a format like;
```
Mozilla/5.0 (compatible; TLS Inspector/$VERSION; +https://tlsinspector.com/)
```

This sticks with existing expectations, while identifying the app, and providing a reference point in case someone wants to find out more about what it is?

**Comment by ecnepsnai** [comment]
@sindarina I've changed the user agent to include a URL to the project in this commit: https://github.com/certificate-helper/TLS-Inspector/commit/4df8eb3dc00dbd5d06789332af746fb775a3fd09

Technically TLS Inspector is not compatible with Mozilla since it does not include a rendering engine so I'm omitting the legacy `Mozilla/5.0 compatible` string.

**Comment by sindarina** [comment]
The point isn't whether it's actually compatible, but about what various filters and such expect, which is why the entire string is recommended.

**Comment by ecnepsnai** [comment]
https://en.wikipedia.org/wiki/User_agent#Format_for_human-operated_web_browsers

> Mozilla/5.0: Previously used to indicate compatibility with the Mozilla rendering engine.

I'm okay with TLS Inspector not being compatible with web servers that have restrictive requirements on user agents.

**Comment by sindarina** [comment]
Well, then you might as well stick with not setting the user agent. Good luck!
