### ISSUE TITLE
Error messages should be displayed 

### ISSUE THREAD

**Issue by keltia** [certificate-helper/TLS-Inspector#86]
**Affected Version:**

1.6.1 (33) 

**Is this a Test Flight version or the App Store version?**
Appstore 

**Device and iOS Version:**
IPhone 7, iOS 11.1.2

**What steps will reproduce the problem?**

1. Try to inspect blog.keltia.net 
2. Watch it display "one or more errors while inspecting…"
3.

**What is the expected output?**
A list of errors, not just that generic message 

**What do you see instead?**

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment]
Hi @keltia,

I agree with your request. I think I had planned to show more detailed information about errors but just forgot to implement it.
