### ISSUE TITLE
Spaces after (and before) the site name should be trimmed out 

### ISSUE THREAD

**Issue by keltia** [certificate-helper/TLS-Inspector#87]
**Affected Version:**

1.6.1 (33)

**Is this a Test Flight version or the App Store version?**
Appstore 

**Device and iOS Version:**
IPhone 7, iOS 11.1.2

**What steps will reproduce the problem?**

1. Begin to type a site name that is in the completion list (you typed it before)
2. Accept the completion, see the space automatically added at the end 
3. Hit inspect 

**What is the expected output?**

TLS analysis 

**What do you see instead?**
Dialog box saying the host is invalid 

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment]
Hi @keltia 

Thanks for finding this, must've slipped past me during testing.
