### ISSUE TITLE
Not-Yet-Valid Certificates show as "Expired"

### ISSUE THREAD

**Issue by ecnepsnai** [certificate-helper/TLS-Inspector#99]
**Affected Version:**

1.7.0

**Is this a Test Flight version or the App Store version?**

App Store

**Device and iOS Version:**

All

**What steps will reproduce the problem?**

1. Inspect a site with a certificate that is not-yet-valid

**What is the expected output?**

Certificate shows as "Not Yet Valid"

**What do you see instead?**

Certificate shows as "Expired"

**Please provide any additional information below.**

**Comment by Bethannfrum** [comment]
Fix and restore to original form and release old documents
